-- Script de réinitialisation SQLite pour BpmPlus
-- Remplacer BPM par le préfixe configuré
-- ATTENTION : supprime toutes les données existantes

-- ============================================================
-- SUPPRESSION (ordre inverse des dépendances)
-- ============================================================

DROP INDEX  IF EXISTS IDX_BPM_SIGNAL_NOM;
DROP TABLE  IF EXISTS BPM_ATTENTE_SIGNAL;
DROP TABLE  IF EXISTS BPM_EVENEMENT_INSTANCE;
DROP TABLE  IF EXISTS BPM_VARIABLE_PROCESSUS;
DROP INDEX  IF EXISTS IDX_BPM_INST_AGGID;
DROP TABLE  IF EXISTS BPM_INSTANCE_PROCESSUS;
DROP TABLE  IF EXISTS BPM_DEFINITION_PROCESSUS;

-- ============================================================
-- CRÉATION
-- ============================================================

CREATE TABLE BPM_DEFINITION_PROCESSUS (
    ID               INTEGER PRIMARY KEY AUTOINCREMENT,
    CLE              TEXT    NOT NULL,
    VERSION          INTEGER NOT NULL,
    NOM              TEXT    NOT NULL,
    STATUT           TEXT    NOT NULL,
    DEFINITION_JSON  TEXT    NOT NULL,
    DATE_CREATION    TEXT    NOT NULL,
    DATE_PUBLICATION TEXT    NULL,
    UNIQUE(CLE, VERSION)
);

CREATE TABLE BPM_INSTANCE_PROCESSUS (
    ID                  INTEGER PRIMARY KEY AUTOINCREMENT,
    CLE_DEFINITION      TEXT    NOT NULL,
    VERSION_DEFINITION  INTEGER NOT NULL,
    AGGREGATE_ID        INTEGER NOT NULL,
    STATUT              TEXT    NOT NULL,
    ID_NOEUD_COURANT    TEXT    NULL,
    ID_INSTANCE_PARENT  INTEGER NULL,
    DATE_DEBUT          TEXT    NOT NULL,
    DATE_FIN            TEXT    NULL,
    DATE_CREATION       TEXT    NOT NULL,
    DATE_MAJ            TEXT    NOT NULL
);
CREATE INDEX IDX_BPM_INST_AGGID ON BPM_INSTANCE_PROCESSUS(AGGREGATE_ID);

CREATE TABLE BPM_VARIABLE_PROCESSUS (
    ID          INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_INSTANCE INTEGER NOT NULL,
    NOM         TEXT    NOT NULL,
    TYPE        TEXT    NOT NULL,
    VALEUR      TEXT,
    UNIQUE(ID_INSTANCE, NOM)
);

CREATE TABLE BPM_EVENEMENT_INSTANCE (
    ID             INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_INSTANCE    INTEGER NOT NULL,
    TYPE_EVENEMENT TEXT    NOT NULL,
    ID_NOEUD       TEXT    NULL,
    NOM_NOEUD      TEXT    NULL,
    HORODATAGE     TEXT    NOT NULL,
    DUREE_MS       INTEGER NULL,
    RESULTAT       TEXT    NULL,
    DETAIL         TEXT    NULL
);

CREATE TABLE BPM_ATTENTE_SIGNAL (
    ID            INTEGER PRIMARY KEY AUTOINCREMENT,
    ID_INSTANCE   INTEGER NOT NULL,
    NOM_SIGNAL    TEXT    NOT NULL,
    DATE_CREATION TEXT    NOT NULL
);
CREATE INDEX IDX_BPM_SIGNAL_NOM ON BPM_ATTENTE_SIGNAL(NOM_SIGNAL);
