-- Script DDL Oracle pour BpmPlus
-- Remplacer BPM par le préfixe configuré

-- Séquences
CREATE SEQUENCE BPM_SEQ_DEFINITION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BPM_SEQ_INSTANCE   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BPM_SEQ_VARIABLE   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BPM_SEQ_EVENEMENT  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BPM_SEQ_SIGNAL     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Table des définitions de processus
CREATE TABLE BPM_DEFINITION_PROCESSUS (
    ID               NUMBER(19)    NOT NULL,
    CLE              VARCHAR2(100) NOT NULL,
    VERSION          NUMBER(10)    NOT NULL,
    NOM              VARCHAR2(200) NOT NULL,
    STATUT           VARCHAR2(20)  NOT NULL,
    DEFINITION_JSON  CLOB          NOT NULL,
    DATE_CREATION    TIMESTAMP     NOT NULL,
    DATE_PUBLICATION TIMESTAMP     NULL,
    CONSTRAINT PK_BPM_DEF PRIMARY KEY (ID),
    CONSTRAINT UQ_BPM_DEF_CLE_VER UNIQUE (CLE, VERSION),
    CONSTRAINT CK_BPM_DEF_STATUT CHECK (STATUT IN ('Brouillon', 'Publiee'))
);

-- Table des instances de processus
CREATE TABLE BPM_INSTANCE_PROCESSUS (
    ID                  NUMBER(19)    NOT NULL,
    CLE_DEFINITION      VARCHAR2(100) NOT NULL,
    VERSION_DEFINITION  NUMBER(10)    NOT NULL,
    AGGREGATE_ID        NUMBER(19)    NOT NULL,
    STATUT              VARCHAR2(20)  NOT NULL,
    ID_NOEUD_COURANT    VARCHAR2(100) NULL,
    ID_INSTANCE_PARENT  NUMBER(19)    NULL,
    DATE_DEBUT          TIMESTAMP     NOT NULL,
    DATE_FIN            TIMESTAMP     NULL,
    DATE_CREATION       TIMESTAMP     NOT NULL,
    DATE_MAJ            TIMESTAMP     NOT NULL,
    CONSTRAINT PK_BPM_INST PRIMARY KEY (ID),
    CONSTRAINT CK_BPM_INST_STATUT CHECK (STATUT IN ('Active', 'Suspendue', 'EnErreur', 'Terminee'))
);
CREATE INDEX IDX_BPM_INST_AGGID ON BPM_INSTANCE_PROCESSUS(AGGREGATE_ID);

-- Table des variables de processus
CREATE TABLE BPM_VARIABLE_PROCESSUS (
    ID          NUMBER(19)     NOT NULL,
    ID_INSTANCE NUMBER(19)     NOT NULL,
    NOM         VARCHAR2(200)  NOT NULL,
    TYPE        VARCHAR2(20)   NOT NULL,
    VALEUR      VARCHAR2(2000) NOT NULL,
    CONSTRAINT PK_BPM_VAR PRIMARY KEY (ID),
    CONSTRAINT UQ_BPM_VAR_INST_NOM UNIQUE (ID_INSTANCE, NOM),
    CONSTRAINT FK_BPM_VAR_INST FOREIGN KEY (ID_INSTANCE) REFERENCES BPM_INSTANCE_PROCESSUS(ID)
);

-- Table des événements d'instance
CREATE TABLE BPM_EVENEMENT_INSTANCE (
    ID              NUMBER(19)    NOT NULL,
    ID_INSTANCE     NUMBER(19)    NOT NULL,
    TYPE_EVENEMENT  VARCHAR2(50)  NOT NULL,
    ID_NOEUD        VARCHAR2(100) NULL,
    NOM_NOEUD       VARCHAR2(200) NULL,
    HORODATAGE      TIMESTAMP     NOT NULL,
    DUREE_MS        NUMBER(19)    NULL,
    RESULTAT        VARCHAR2(20)  NULL,
    DETAIL          CLOB          NULL,
    CONSTRAINT PK_BPM_EVT PRIMARY KEY (ID),
    CONSTRAINT FK_BPM_EVT_INST FOREIGN KEY (ID_INSTANCE) REFERENCES BPM_INSTANCE_PROCESSUS(ID)
);

-- Table des attentes de signal
CREATE TABLE BPM_ATTENTE_SIGNAL (
    ID            NUMBER(19)    NOT NULL,
    ID_INSTANCE   NUMBER(19)    NOT NULL,
    NOM_SIGNAL    VARCHAR2(200) NOT NULL,
    DATE_CREATION TIMESTAMP     NOT NULL,
    CONSTRAINT PK_BPM_SIG PRIMARY KEY (ID),
    CONSTRAINT FK_BPM_SIG_INST FOREIGN KEY (ID_INSTANCE) REFERENCES BPM_INSTANCE_PROCESSUS(ID)
);
CREATE INDEX IDX_BPM_SIG_NOM ON BPM_ATTENTE_SIGNAL(NOM_SIGNAL);
