-- Script DDL Oracle pour BpmPlus
-- Remplacer BPM par le préfixe configuré

-- Séquences
CREATE SEQUENCE BPM_SEQ_DEFIN      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BPM_SEQ_INSTC      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BPM_SEQ_VAR_PROCS  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BPM_SEQ_EVEN_INSTC START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE BPM_SEQ_SIGNL      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Table des définitions de processus
CREATE TABLE BPM_DEFIN_PROCS (  --BPM_DEFINITION_PROCESSUS
    NO_SEQ_DEFIN_PROCS NUMBER(19)    NOT NULL, --ID
    CLE                VARCHAR2(100) NOT NULL,
    VERSI              NUMBER(10)    NOT NULL, --VERSION
    NOM_DEFIN          VARCHAR2(200) NOT NULL, --NOM
    STAT               VARCHAR2(20)  NOT NULL, --STATUT
    DEFIN_JSON         CLOB          NOT NULL, --DEFINITION_JSON
    DH_CREA            DATE          NOT NULL, --DATE_CREATION
    DH_PUBL            DATE          NULL,     --DATE_PUBLICATION
    CONSTRAINT PK_BPM_DEF PRIMARY KEY (NO_SEQ_DEFIN_PROCS),
    CONSTRAINT UQ_BPM_DEF_CLE_VER UNIQUE (CLE, VERSI),
    CONSTRAINT CK_BPM_DEF_STAT CHECK (STAT IN ('Brouillon', 'Publiee'))
);

-- Table des instances de processus
CREATE TABLE BPM_INSTC_PROCS (  --BPM_INSTANCE_PROCESSUS
    NO_SEQ_INSTC_PROCS NUMBER(19)    NOT NULL, --ID
    CLE_DEFIN          VARCHAR2(100) NOT NULL, --CLE_DEFINITION
    VERSI_DEFIN        NUMBER(10)    NOT NULL, --VERSION_DEFINITION
    AGGRE_ID           NUMBER(19)    NOT NULL, --AGGREGATE_ID
    STAT               VARCHAR2(20)  NOT NULL, --STATUT
    ID_NOEUD_COUR      VARCHAR2(100) NULL,     --ID_NOEUD_COURANT
    ID_INSTC_PARN      NUMBER(19)    NULL,     --ID_INSTANCE_PARENT
    DH_DEB             DATE          NOT NULL, --DATE_DEBUT
    DH_FIN             DATE          NULL,     --DATE_FIN
    DH_CREA            DATE          NOT NULL, --DATE_CREATION
    DH_MODIF           DATE          NOT NULL, --DATE_MAJ
    LOGON_ASSIG        VARCHAR2(100) NULL,     --LOGON_ASSIGNE
    LOGON_TACH_PREC    VARCHAR2(100) NULL,     --LOGON_TACHE_PRECEDENTE
    CONSTRAINT PK_BPM_INSTC_PROCS PRIMARY KEY (NO_SEQ_INSTC_PROCS),
    CONSTRAINT CK_BPM_INSTC_STAT CHECK (STAT IN ('Active', 'Suspendue', 'EnErreur', 'Terminee'))
);
CREATE INDEX IDX_BPM_INST_AGGID ON BPM_INSTC_PROCS(AGGRE_ID);

-- Table des variables de processus
CREATE TABLE BPM_VAR_PROCS (  --BPM_VARIABLE_PROCESSUS
    NO_SEQ_VAR_PROCS   NUMBER(19)     NOT NULL, --ID
    NO_SEQ_INSTC_PROCS NUMBER(19)     NOT NULL, --ID_INSTANCE
    NOM_VAR            VARCHAR2(200)  NOT NULL, --NOM
    TYP_VAR            VARCHAR2(20)   NOT NULL, --TYPE
    VAL_VAR            VARCHAR2(2000) NULL,     --VALEUR
    CONSTRAINT PK_BPM_VAR PRIMARY KEY (NO_SEQ_VAR_PROCS),
    CONSTRAINT UQ_BPM_VAR_INST_NOM UNIQUE (NO_SEQ_INSTC_PROCS, NOM_VAR),
    CONSTRAINT FK_BPM_VAR_INST FOREIGN KEY (NO_SEQ_INSTC_PROCS) REFERENCES BPM_INSTC_PROCS(NO_SEQ_INSTC_PROCS)
);

-- Table des événements d'instance
CREATE TABLE BPM_EVEN_INSTC_PROCS (  --BPM_EVENEMENT_INSTANCE
    NO_SEQ_EVEN_INSTC_PROCS NUMBER(19)    NOT NULL, --ID
    NO_SEQ_INSTC_PROCS      NUMBER(19)    NOT NULL, --ID_INSTANCE
    TYP_EVEN                VARCHAR2(50)  NOT NULL, --TYPE_EVENEMENT
    ID_NOEUD                VARCHAR2(100) NULL,
    NOM_NOEUD               VARCHAR2(200) NULL,
    DH_CREA                 DATE          NOT NULL, --HORODATAGE
    DUR_MS                  NUMBER(19)    NULL,     --DUREE_MS
    RESUL                   VARCHAR2(20)  NULL,     --RESULTAT
    DETL                    CLOB          NULL,     --DETAIL
    CONSTRAINT PK_BPM_EVT PRIMARY KEY (NO_SEQ_EVEN_INSTC_PROCS),
    CONSTRAINT FK_BPM_EVT_INST FOREIGN KEY (NO_SEQ_INSTC_PROCS) REFERENCES BPM_INSTC_PROCS(NO_SEQ_INSTC_PROCS)
);

-- Table des attentes de signal
CREATE TABLE BPM_ATTEN_SIGNL (  --BPM_ATTENTE_SIGNAL
    NO_SEQ_ATTEN_SIGNL NUMBER(19)    NOT NULL, --ID
    NO_SEQ_INSTC_PROCS NUMBER(19)    NOT NULL, --ID_INSTANCE
    NOM_SIGNL          VARCHAR2(200) NOT NULL, --NOM_SIGNAL
    DH_CREA            DATE          NOT NULL, --DATE_CREATION
    CONSTRAINT PK_BPM_SIG PRIMARY KEY (NO_SEQ_ATTEN_SIGNL),
    CONSTRAINT FK_BPM_SIG_INST FOREIGN KEY (NO_SEQ_INSTC_PROCS) REFERENCES BPM_INSTC_PROCS(NO_SEQ_INSTC_PROCS)
);
CREATE INDEX IDX_BPM_SIG_NOM ON BPM_ATTEN_SIGNL(NOM_SIGNL);
